config/routes.rb
Rails.application.routes.draw do
  resources :send_mails
  get 'send_mail/send_mail'

  get 'get_ip/get_ip'

  get 'parse_json/json_parser'

  resource :get_ip, controller: :get_ip

  root to: "get_ip#get_ip"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/send_mail.rb
class SendMail < ApplicationRecord
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/get_ip_controller.rb
class GetIpController < ApplicationController
  def get_ip
   #@public_ip = Net::HTTP.get URI "https://api.ipify.org"
    @public_ip = '116.73.132.131'
    @details =  Geocoder.address(@public_ip)
  end
end

app/controllers/send_mails_controller.rb
class SendMailsController < ApplicationController
  before_action :set_send_mail, only: [:show, :edit, :update, :destroy]

  # GET /send_mails
  # GET /send_mails.json
  def index
    @send_mails = SendMail.all
  end

  # GET /send_mails/1
  # GET /send_mails/1.json
  def show
  end

  # GET /send_mails/new
  def new
    @send_mail = SendMail.new
  end

  # GET /send_mails/1/edit
  def edit
  end

  # POST /send_mails
  # POST /send_mails.json
  def create
    @send_mail = SendMail.new(send_mail_params)

    respond_to do |format|
      if @send_mail.save
        ExampleMailer.sampleemail(@send_mail).deliver


        format.html { redirect_to @send_mail, notice: 'Send mail was successfully created.' }
        format.json { render :show, status: :created, location: @send_mail }
      else
        format.html { render :new }
        format.json { render json: @send_mail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /send_mails/1
  # PATCH/PUT /send_mails/1.json
  def update
    respond_to do |format|
      if @send_mail.update(send_mail_params)
        format.html { redirect_to @send_mail, notice: 'Send mail was successfully updated.' }
        format.json { render :show, status: :ok, location: @send_mail }
      else
        format.html { render :edit }
        format.json { render json: @send_mail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /send_mails/1
  # DELETE /send_mails/1.json
  def destroy
    @send_mail.destroy
    respond_to do |format|
      format.html { redirect_to send_mails_url, notice: 'Send mail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_send_mail
      @send_mail = SendMail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def send_mail_params
      params.require(:send_mail).permit(:email, :string)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/get_ip_helper.rb
module GetIpHelper
end

app/helpers/send_mails_helper.rb
module SendMailsHelper
end

app/views/get_ip/get_ip.html.erb
<h2>Assignment</h2>

<h2>Question:1</h2>
<b>IP:&nbsp;&nbsp;</b><%= @public_ip %><br />
<b>IP:&nbsp;&nbsp;</b><%= @details %><br />


<h2>Question:2</h2>
<p>Write code to accept recipient email id and message from a screen and send email using SMTP .</p>
<p>Click on link below to collect email id and send mail</p>
<%= link_to 'Send Mail', send_mails_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/send_mails/_form.html.erb
<%= form_with(model: send_mail, local: true) do |form| %>
  <% if send_mail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(send_mail.errors.count, "error") %> prohibited this send_mail from being saved:</h2>

      <ul>
      <% send_mail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :send_mail_email %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/send_mails/edit.html.erb
<h1>Editing Send Mail</h1>

<%= render 'form', send_mail: @send_mail %>

<%= link_to 'Show', @send_mail %> |
<%= link_to 'Back', send_mails_path %>

app/views/send_mails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Send Mails</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>String</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @send_mails.each do |send_mail| %>
      <tr>
        <td><%= send_mail.email %></td>
        <td><%= link_to 'Show', send_mail %></td>
        <td><%= link_to 'Edit', edit_send_mail_path(send_mail) %></td>
        <td><%= link_to 'Destroy', send_mail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Send Mail', new_send_mail_path %>

app/views/send_mails/new.html.erb
<h1>New Send Mail</h1>

<%= render 'form', send_mail: @send_mail %>

<%= link_to 'Back', send_mails_path %>

app/views/send_mails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @send_mail.email %>
</p>


<%= link_to 'Edit', edit_send_mail_path(@send_mail) %> |
<%= link_to 'Back', send_mails_path %>